name: Puppeteer Action

on:
  push:
    branches:
      - main

jobs:
  puppeteer_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      

    - name: Run Puppeteer using GHCR Docker image with fixed .npmrc permissions
      run: |
        docker run --rm -v ${{ github.workspace }}:/home/pptruser/app \
        --user $(id -u):$(id -g) \
        ghcr.io/puppeteer/puppeteer:latest \
        /bin/bash -c "mkdir -p /home/pptruser/.npm && touch /home/pptruser/.npmrc && npm config set cache /home/pptruser/.npm && npm config set userconfig /home/pptruser/.npmrc && cd /home/pptruser/app && npm install && node /home/pptruser/app/screenshot.js"


    - name: Upload Screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: ./screenshots/screenshot.png
