name: Puppeteer Action

on:
  push:
    branches:
      - main

jobs:
  puppeteer_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Puppeteer using GHCR Docker image
      run: |
        # Run the container, mount the repository to /home/pptruser/app, install dependencies, and run Puppeteer
        docker run --rm -v ${{ github.workspace }}:/home/pptruser/app ghcr.io/puppeteer/puppeteer:latest \
        /bin/bash -c "cd /home/pptruser/app && chown -R $(id -u):$(id -g) /home/pptruser/app && npm install --unsafe-perm=true && node /home/pptruser/app/screenshot.js"

    - name: Upload Screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: ./screenshots/screenshot.png
