name: Puppeteer Action

on:
  push:
    branches:
      - main

jobs:
  puppeteer_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Puppeteer using GHCR Docker image
      run: |
        # Run the container, mount the repository, and install dependencies
        docker run --rm -v ${{ github.workspace }}:/usr/src/app ghcr.io/puppeteer/puppeteer:latest \
        /bin/bash -c "cd /usr/src/app && npm install && node /usr/src/app/screenshot.js"

    - name: Upload Screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: ./screenshots/screenshot.png
