name: Puppeteer Action

on:
  push:
    branches:
      - main

jobs:
  puppeteer_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Puppeteer using GHCR Docker image with UID/GID override
      run: |
        # Override the UID and GID to match the runner's UID (1001) and GID (127) when running the container
        docker run --rm -v ${{ github.workspace }}:/home/pptruser/app \
        --user $(id -u):$(id -g) \
        ghcr.io/puppeteer/puppeteer:latest \
        /bin/bash -c "cd /home/pptruser/app && npm install && node /home/pptruser/app/screenshot.js"

    - name: Upload Screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: ./screenshots/screenshot.png
