name: Puppeteer Action

on:
  push:
    branches:
      - main

jobs:
  puppeteer_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run Puppeteer using GHCR Docker image with fixed cache permissions
      run: |
        # Fix the cache permissions before running npm install
        docker run --rm -v ${{ github.workspace }}:/home/pptruser/app \
        --user $(id -u):$(id -g) \
        ghcr.io/puppeteer/puppeteer:latest \
        /bin/bash -c "npm cache clean --force && mkdir -p /home/pptruser/.npm && npm config set cache /home/pptruser/.npm && cd /home/pptruser/app && npm install && node /home/pptruser/app/screenshot.js"
        

    - name: Upload Screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: ./screenshots/screenshot.png
